### ISSUE TITLE
Raise limit of 'list' sub-command

### ISSUE THREAD

**Issue by asherbender** [ivcap-works/ivcap-cli#26]
The `list` sub-command limits the number of rows that can be returned. For example:

https://github.com/ivcap-works/ivcap-cli/blob/d96c056af574f090be67fbce163e443fd08a6c8a/cmd/artifact.go#L137

As systems get larger, this limit become restrictive. An 'easy' solution is to raise the limit of returned results. A more elegant solution would be to provide users crude control over what results are returned (see #25).

**Comment by maxott** [comment]
That is primarily meant to protect the system and keep it responsive. There is always 'page' to page through the list. 

We may increase that limit when we have a more efficient way to retrieve the list. RIght now, every item needs to be verified by OPA to ensure that the requester can actually see it

**Comment by maxott** [comment]
May revisit later. The IVCAP client-sdk for instance takes care of that in the background with the user only seeing an iterator
